# Header
nav:
  Posts: /archives
  Categories: /categories
  Tags: /tags
  About: /about

# favicon
favicon: /favicon.png

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/faketut
  LinkedIn: https://www.linkedin.com/in/jack-jf
  # Twitter:
  # Weibo:

# share post actions
share_post:
  enable: true
  # QR code generator base URL for WeChat share
  # default: https://api.qrserver.com/v1/create-qr-code/
  qr_api_base: https://api.qrserver.com/v1/create-qr-code/
  platforms:
    twitter: true
    linkedin: true
    facebook: true
    reddit: true
    weibo: true
    qq: true
    wechat: true

# ads
ads:
  enable: true
  adsterra:
    enable: true
    # script url provided by ad network
    js: https://pl29242202.profitablecpmratenetwork.com/5fe41348fd7f700b5708c1c2a2c623f8/invoke.js
    # container id provided by ad network
    div_id: container-5fe41348fd7f700b5708c1c2a2c623f8

# analytics
google_analytics: G-F0FD4FHZKL
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: false

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: faketut/faketut.github.io
  repo_id: R_kgDOSKOmOw
  category: General
  category_id: DIC_kwDOSKOmO84C7nVi
  mapping: pathname
  lang: en

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

